trigger:
- master
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'DemoServiceARM'
    subscriptionId: 'e9926545-2efb-4941-8934-7eb8d65487b2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DemoARM'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'DemoTemplateARM/template.json'
    overrideParameters: '-projectName DemoTemplateARM -linkedTemplateUri https://raw.githubusercontent.com/kaus1995/DemoTemplateARM/master/parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'